steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','asia-northeast1-docker.pkg.dev/project-83e7d21c-5b76-435e-98f/apps/abc-app:\','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','asia-northeast1-docker.pkg.dev/project-83e7d21c-5b76-435e-98f/apps/abc-app:\']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-lc'
    - |
      gcloud run deploy abc-app \
        --image asia-northeast1-docker.pkg.dev/project-83e7d21c-5b76-435e-98f/apps/abc-app:\ \
        --region asia-northeast1 \
        --platform managed \
        --quiet
      URL=\https://abc-app-ilyizdkoja-an.a.run.app
      echo "SERVICE_URL=\"
      curl -fsS "\/health" >/dev/null
      echo "SMOKE=OK"
images:
- 'asia-northeast1-docker.pkg.dev/project-83e7d21c-5b76-435e-98f/apps/abc-app:\'
